// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  engine: 'classic',
  datasource: {
    // `prisma generate`는 스키마 파일만 읽고 DB에 연결하지 않으므로 DATABASE_URL이
    // 없어도 동작해야 한다. env('DATABASE_URL')(strict)은 이 경우에도 무조건 throw해서
    // CI(npm ci → postinstall → prisma generate)가 DATABASE_URL 없이 매번 실패했다.
    // 로컬(.env)/배포(ECS 런타임 SSM 주입) 시에는 실제 값이 들어와 정상 동작한다.
    url:
      process.env.DATABASE_URL ?? 'postgresql://placeholder:placeholder@localhost:5432/placeholder',
  },
});
